### ISSUE TITLE
[PE-D][Tester A] Help guide still pointing to addressbook instead of your group's user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-3/tp#142] opened 2023-03-31 19:38 UTC
![Screenshot 2023-03-31 at 3.17.54 PM.png](https://raw.githubusercontent.com/ZhuLeYao/ped/main/files/78d609bd-83e1-455b-978d-2ae6272cea16.png)

Remember to update the help guide link to your UG instead of the addressbook :)!

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ZhuLeYao/ped#11

**Comment by CloudHill** [comment] 2023-04-09 05:37
Duplicate of #110

**Closed as not planned by CloudHill** 2023-04-09 05:37 UTC
Labels: duplicate
