### ISSUE TITLE
[PE-D][Tester A] Incomplete user guide for customer rewarding tutorial

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-3/tp#135] opened 2023-03-31 19:13 UTC
![Screenshot 2023-03-31 at 3.01.11 PM.png](https://raw.githubusercontent.com/ZhuLeYao/ped/main/files/12724b3f-6778-4cc9-8d10-acbcc5cff14b.png)

Incomplete user guide for a tutorial on how to reward customers.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: ZhuLeYao/ped#9

**Comment by CloudHill** [comment] 2023-04-09 05:36
Duplicate of #125

**Closed as not planned by CloudHill** 2023-04-09 05:36 UTC
Labels: duplicate
